### ISSUE TITLE
Some additions

### ISSUE THREAD

**Issue by sgtpep** [mrzool/bash-sensible#1]
I'll try to contribute in free-form style:
- `set -o noclobber`
- `shopt -s checkwinsize`
- `stty -ixon`
- `PROMPT_DIRTRIM=2`
- `. /usr/lib/git-core/git-sh-prompt`
- show the last command exit status message: `PROMPT_COMMAND='_status=$?; [[ $_status == 0 ]] || echo -e "\e[4mExit status: $_status\e[m"; '$PROMPT_COMMAND`

**Comment by mrzool** [comment]
`set -o noclobber`, `shopt -s checkwinsize` and `PROMPT_DIRTRIM=2` look perfect, I'll add them in.

I would leave out `git-prompt.sh` because it's git-specific and not everyone uses git. The last one looks pretty invasive and, as far as I can tell, would break the [rule of silence](http://www.linfo.org/rule_of_silence.html). Why would I want to know the exit status of every command I run?

After some googling I'm still not sure what `stty -ixon` does, but it's late here right now so I'll look it up again tomorrow.

Thanks for the input!

**Comment by sgtpep** [comment]
> I'm still not sure what stty -ixon does

It's one of the ways to disable terminal freezing by accidentally pressing Ctrl-S. Also Ctrl-S is the default readline shortcut for quite useful forward-search-history. This readline command behaves buggy on debian-jessie but OK on arch-linux. When it's not buggy Ctrl-S is a nice addition to Ctrl-R for quick history navigation.

> Why would I want to know the exit status of every command I run?

Sorry for unclear explanation. This snippet only shows the exit status that is different than the successful one (0). Some scripts or commands fail sometimes without any output, or output is not clear. This notification helps you to know that something went wrong. This kind of notification is popular among zsh users, and zsh allows activate it much easier: http://stackoverflow.com/q/4466245/852439. Also I was using the simpler version of this in bash: `trap 'echo -e "\e[4mExit code: $?\e[m" >&2' ERR`, but unfortunately it occasionally stops working during the interactive session.
