### ISSUE TITLE
Up-to-date Bash on OS X

### ISSUE THREAD

**Issue by jfexyz** [mrzool/bash-sensible#9]
What is the recommended version of bash-completion?
- Mac OS X 10.11.3
- bash 4.3.42(1)-release (via `brew install bash`)

With bash-completion 1.3 (`brew install bash-completion`), I'm getting the following error:

``` shell
-bash: shopt: dirspell: invalid shell option name
```

With bash-completion 2.1 (`brew install bash-completion2`), I'm getting the following errors:

``` shell
-bash: shopt: dirspell: invalid shell option name
-bash: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
-bash: complete: -D: invalid option
complete: usage: complete [-abcdefgjksuv] [-pr] [-o option] [-A action] [-G globpat] [-W wordlist] [-P prefix] [-S suffix] [-X filterpat] [-F function] [-C command] [name ...]
```

**Comment by jwhitmarsh** [comment]
Ditto - OSX 10.11.3, bash 4.3.42, bash-completion 1.3 - same error message

**Comment by robsonpeixoto** [comment]
@jwhitmarsh, @joshuajabbour `brew install homebrew/versions/bash-completion2`

**Comment by jwhitmarsh** [comment]
This was actually my mistake in the end - I had bash v4 installed via brew (in /usr/local/bin/bash), but was still running bash v3 (from /bin/bash). Ended up switch it with `chsh`.

**Comment by mrzool** [comment]
Using Bash 4.x will ensure that all the options in Sensible Bash will work out of the box.

It's generally a good idea to edit your `/etc/paths` file so that the binaries installed by homebrew have higher priority than the binaries shipped with OS X. See how to do that [here](http://stackoverflow.com/questions/10343834/homebrew-wants-me-to-amend-my-path-no-clue-how). Having homebrew properly configured will spare you the hassle of having to use ad-hoc tools like `chsh`.

To install and configure Bash Completion on OS X, check out [this post](http://davidalger.com/development/bash-completion-on-os-x-with-brew/).

**Comment by mrzool** [comment]
Also, read [this](http://alistapart.com/article/the-path-to-enlightenment) to understand all about this `$PATH` and `/etc/paths` thing.

**Comment by jfexyz** [comment]
Everything works properly except bash-sensible, I've been using completions successfully for years, and am def on bash 4. But I guess this is solved in your mind...

**Comment by mrzool** [comment]
Are you positive that you're on Bash 4?

`bash --version`

**Comment by jwhitmarsh** [comment]
Also worth checking `echo $BASH_VERSION` as that is how I discovered I was using the wrong executable.

**Comment by jfexyz** [comment]
``` shell
pancakes:~ joshua$ bash --version
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.0.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
pancakes:~ joshua$ echo $BASH_VERSION
3.2.57(1)-release
```

Ok, so that is something.

**Comment by jfexyz** [comment]
My homebrew is set up to be favored over stock Apple binaries, so I guess I'll have to go the `chsh` route

**Comment by jwhitmarsh** [comment]
Yeah it's weird, I checked @mrzool's advice about $PATH and mine looks to be setup correctly too. Glad you found out what's wrong though.

**Comment by mrzool** [comment]
Good catch @jwhitmarsh. Apparently `bash --version` is not as reliable as the environment variable `$BASH_VERSION` in telling you which Bash are you actually using.

So, it turns out that in order to use an up-to-date Bash on OS X setting up the `$PATH` properly is not enough. According to [this article](https://johndjameson.com/blog/updating-your-shell-with-homebrew/), you'll also need to append Bash’s path to `/etc/shells` and change the system shell globally with `chsh`. The sequence of commands is:

``` bash
brew install bash
echo /usr/local/bin/bash >> /etc/shells
chsh -s /usr/local/bin/bash
```

I'm going to add a mention to this in the readme.

Closing now and editing the title as Bash completion has nothing to do with the issue at hand.

**Comment by jfexyz** [comment]
Awesome. Thanks @jwhitmarsh for your help in figuring this out.

**Comment by jfexyz** [comment]
Though the instructions linked to are actually incorrect. They describe changing the shell for `root`, not your user.

**Comment by Dhana-Krishnasamy** [comment]
I had to follow [this](https://troymccall.com/better-bash-4--completions-on-osx/) to get bash updated to 4.4.19 and bash-completion2 installed without any issues on  osx 10.13.4.
